// <auto-generated />
namespace CatastroAvanza.Identity.DbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Tipo_Y_Documento_Tabla_Usuario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tipo_Y_Documento_Tabla_Usuario));
        
        string IMigrationMetadata.Id
        {
            get { return "202107140006035_Tipo_Y_Documento_Tabla_Usuario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
