// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregadas_Tablas_ActividadDiaria_TipoActividad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregadas_Tablas_ActividadDiaria_TipoActividad));
        
        string IMigrationMetadata.Id
        {
            get { return "202106070311102_Agregadas_Tablas_ActividadDiaria_TipoActividad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
