// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adicion_columna_FInsercion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adicion_columna_FInsercion));
        
        string IMigrationMetadata.Id
        {
            get { return "202106300129332_adicion_columna_FInsercion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
