// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class crea_tabla_actividad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crea_tabla_actividad));
        
        string IMigrationMetadata.Id
        {
            get { return "202105240254145_crea_tabla_actividad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
