// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Elimina_Columna_Requiere_Visita_Tabla_Actividad : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Elimina_Columna_Requiere_Visita_Tabla_Actividad));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060444548_Elimina_Columna_Requiere_Visita_Tabla_Actividad"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
