// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregadas_columnas_para_nombre_archivos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregadas_columnas_para_nombre_archivos));
        
        string IMigrationMetadata.Id
        {
            get { return "202105262255321_Agregadas_columnas_para_nombre_archivos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
