// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Agregadas_tablas_actividades_y_catalogos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agregadas_tablas_actividades_y_catalogos));
        
        string IMigrationMetadata.Id
        {
            get { return "202105150620051_Agregadas_tablas_actividades_y_catalogos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
