// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_IdtrabajoParent_trabajo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IdtrabajoParent_trabajo));
        
        string IMigrationMetadata.Id
        {
            get { return "202108260142028_Add_IdtrabajoParent_trabajo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
