// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nuevas_columnas_tabla_actividades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nuevas_columnas_tabla_actividades));
        
        string IMigrationMetadata.Id
        {
            get { return "202106220446316_nuevas_columnas_tabla_actividades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
