// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modificacion_columnas_areas_de_entero_a_decimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificacion_columnas_areas_de_entero_a_decimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202106090430416_Modificacion_columnas_areas_de_entero_a_decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
