// <auto-generated />
namespace CatastroAvanza.Repositorio.DBContexto.Migraciones
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class columna_estado_carga_archivo_tabla_archivo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columna_estado_carga_archivo_tabla_archivo));
        
        string IMigrationMetadata.Id
        {
            get { return "202108200245185_columna_estado_carga_archivo_tabla_archivo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
